import type { Metadata } from "next";
import { ColorModeScript, Container, UIProvider } from "@yamada-ui/react";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body suppressHydrationWarning>
        <ColorModeScript initialColorMode="dark" />
        <UIProvider>
          <Container centerContent minH="100svh" p="0">
            {children}
          </Container>
        </UIProvider>
      </body>
    </html>
  );
}
